# Generated by Django 4.0.5 on 2022-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('option1_checked', models.IntegerField(default=0)),
                ('option2_checked', models.IntegerField(default=0)),
                ('option3_checked', models.IntegerField(default=0)),
            ],
        ),
    ]
